#!/bin/bash

source `dirname $0`/env.sh 

MALLOC_ARENA_MAX=1; export MALLOC_ARENA_MAX

java -Xmx1536m -Xms1024m -cp "$CLAS12DIR/lib/clas/*:$CLAS12DIR/lib/plugins/*" org.jlab.detector.decode.CLASDecoder $*
