# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Coatjava-CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: build
      run: ./build-coatjava.sh --spotbugs --unittests
    - name: kpp-test
      run: cd validation/advanced-tests && ./run-advanced-tests.sh
    - name: eb-ep-test
      run: cd validation/advanced-tests && ./run-eb-tests.sh -100 electronproton
    - name: eb-eg-test
      run: cd validation/advanced-tests && ./run-eb-tests.sh -100 electrongamma
    - name: eb-epc-test
      run: cd validation/advanced-tests && ./run-eb-tests.sh -100 electronprotonC
    - name: eb-enc-test
      run: cd validation/advanced-tests && ./run-eb-tests.sh -100 electronneutronC
    - name: eb-eftpi-test
      run: cd validation/advanced-tests && ./run-eb-tests.sh -100 electronFTpion

